#!/bin/bash

mkdir $2
cd $2
cat > index.html <<HTML
<!DOCTYPE html>
<html><head><title>Sunvox.space</title><meta charset="utf-8"/>
<meta http-equiv="refresh" content="0; $1"/>
<link rel="shortcut icon" href="https://avatars1.githubusercontent.com/u/23387494?v=3&s=50">
</meta></head></html>
HTML

echo "Created shortlink http://sunvox.space/$2/"
