#!/bin/bash

cat > $2 <<HTML
<!DOCTYPE html>
<!--

Redirect to $1
Shortlink $2

-->
<html>
<head>
<title>Redirecting...</title>
<meta charset="utf-8"/>
<meta http-equiv="refresh" content="0; $1"/>
</head>
</html>
HTML

echo "Created shortlink http://sunvox.space/$2/"
